version: "3"

services:
  apprication:
    build: apprication
    environment:
      JAMES_URL: http://james:8081
    ports:
      - 8080:8080

  james:
    build: james
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DBNAME: goday
    ports:
      - 8081:8081

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: goday
    ports:
      - 5432:5432